import {Heading} from '@chakra-ui/react'
import axios from 'axios'
import type {NextPage} from 'next'
import Head from 'next/head'
import {useQuery} from 'react-query'
import {Tables} from '../components/tables'

const useCircleSnapshot = () =>
  useQuery('circleSnapshot', async () => {
    const response = await axios.get('/api/snapshot')
    return response.data
  })

const Home: NextPage = () => {
  const {isLoading, error, data} = useCircleSnapshot()

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading as="h1">Coordinape Playground</Heading>

        <div>
          {isLoading && <p>Loading...</p>}
          {error && <p>Error: {(error as any).message}</p>}
          {data && <Tables {...data} />}
        </div>
      </main>
    </div>
  )
}

export default Home
